// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUTTC5fDyIAfhM51hQQxh6RoBobPhE3w',
    appId: '1:372441357497:web:b7a0df638bc577fc330f68',
    messagingSenderId: '372441357497',
    projectId: 'bhi-workbase',
    authDomain: 'bhi-workbase.firebaseapp.com',
    storageBucket: 'bhi-workbase.firebasestorage.app',
    measurementId: 'G-WLFVMWJ0M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZU67vluL1wqrtcn84Q94u1ZEUcpKovY',
    appId: '1:372441357497:android:1775e6e0e55d718a330f68',
    messagingSenderId: '372441357497',
    projectId: 'bhi-workbase',
    storageBucket: 'bhi-workbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAghbwSfeX0HV2i8Yt_CjN558UtRAFdSqk',
    appId: '1:372441357497:ios:97a33a7a0c82d542330f68',
    messagingSenderId: '372441357497',
    projectId: 'bhi-workbase',
    storageBucket: 'bhi-workbase.firebasestorage.app',
    iosBundleId: 'com.example.bhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAghbwSfeX0HV2i8Yt_CjN558UtRAFdSqk',
    appId: '1:372441357497:ios:97a33a7a0c82d542330f68',
    messagingSenderId: '372441357497',
    projectId: 'bhi-workbase',
    storageBucket: 'bhi-workbase.firebasestorage.app',
    iosBundleId: 'com.example.bhi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEUTTC5fDyIAfhM51hQQxh6RoBobPhE3w',
    appId: '1:372441357497:web:44b09913c538a191330f68',
    messagingSenderId: '372441357497',
    projectId: 'bhi-workbase',
    authDomain: 'bhi-workbase.firebaseapp.com',
    storageBucket: 'bhi-workbase.firebasestorage.app',
    measurementId: 'G-X648PYFZHD',
  );
}
